name    'vosupport'
version '0.0.1'
author 'schwicke'
license 'Apache License, Version 2.0 (the "License")'
summary 'VO default definitions and setup tools'
description 'This modules provides classes and definitions required to setup a list of supported VOs.'
project_page 'http://www.eu-emi.eu/'
dependency 'puppetlabs/stdlib'
